# Generated by Django 6.0.1 on 2026-01-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='userchat',
            name='sender',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserChat',
        ),
    ]
